#include <hip/hip_runtime.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <limits.h>

#if defined(_WIN32)
#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#else
#include <dlfcn.h>
#endif

#if defined(_MSC_VER)
#define HIP_QUANT_EXPORT __declspec(dllexport)
#else
#define HIP_QUANT_EXPORT __attribute__((visibility("default")))
#endif

#include "kernels/quant_q4_0.cu"
#include "kernels/quant_q4_1.cu"
#include "kernels/quant_q5_0.cu"
#include "kernels/quant_q5_1.cu"
#include "kernels/quant_q8_0.cu"
#include "kernels/quant_q8_1.cu"
#include "kernels/quant_q2_K.cu"
#include "kernels/quant_q3_K.cu"
#include "kernels/quant_q4_K.cu"
#include "kernels/quant_q5_K.cu"
#include "kernels/quant_q6_K.cu"
#include "kernels/quant_iq2_xxs.cu"
#include "kernels/quant_iq2_xs.cu"
#include "kernels/quant_iq1_s.cu"
#include "kernels/quant_iq4_nl.cu"
#include "kernels/quant_iq4_xs.cu"
#include "kernels/quant_iq3_xxs.cu"
#include "kernels/quant_iq3_s.cu"
#include "kernels/quant_tq1_0.cu"
#include "kernels/quant_tq2_0.cu"
#include "kernels/quant_hq2.cu"
#include "kernels/quant_f8_e4m3.cu"
#include "kernels/quant_f8_e5m2.cu"
#include "kernels/fp8_expand.cu"
#include "kernels/dequant_to_fp8.cu"
#include "kernels/fp8_gemm_test.cu"
#include "kernels/wmma_diag.cu"
#include "kernels/direct_fp8_quant.cu"

#define QK_K 256
#define QK8_0 32
#define QK4_0 32
#define QK4_1 32
#define QK5_0 32
#define QK5_1 32
#define QK8_1 32
#define QK4_NL 32
#define QK_F8 32

static bool hip_initialized = false;
static bool iq3xxs_tables_loaded = false;
static bool iq2xxs_tables_loaded = false;
static bool iq2xs_tables_loaded = false;
static bool iq1s_tables_loaded = false;
static bool iq3s_tables_loaded = false;
static int device_id = 0;
static hipDeviceProp_t props;
static int *d_iq2xxs_map_data = NULL;
static uint16_t *d_iq2xxs_neighbours_data = NULL;
static int8_t *d_iq2xs_grid_data = NULL;
static int *d_iq2xs_map_data = NULL;
static uint16_t *d_iq2xs_neighbours_data = NULL;
static int8_t *d_iq1s_grid_data = NULL;
static int *d_iq1s_map_data = NULL;
static uint16_t *d_iq1s_neighbours_data = NULL;
static int8_t *d_iq3s_grid_data = NULL;
static int *d_iq3s_map_data = NULL;
static uint16_t *d_iq3s_neighbours_data = NULL;

// Per-thread cached GPU buffers for quantize_tensor.
// File-scope so quantize_reset() can free them from any thread.
static thread_local float   *g_d_src       = NULL;
static thread_local uint8_t *g_d_src_fp8   = NULL;
static thread_local uint8_t *g_d_dst       = NULL;
static thread_local float   *g_d_imatrix   = NULL;
static thread_local size_t   g_d_src_cap   = 0;
static thread_local size_t   g_d_src_fp8_cap = 0;
static thread_local size_t   g_d_dst_cap   = 0;
static thread_local size_t   g_d_imatrix_cap = 0;

// I-Quant codebooks are runtime assets rather than giant compile-time C++
// arrays.  This keeps the DLL small and lets package updates replace table
// data without recompiling device code.  The binary layout is generated by
// tools/export_iq_codebooks.py and is intentionally little-endian.
#pragma pack(push, 1)
typedef struct {
    char magic[8];
    uint32_t version;
    uint32_t grid_bytes;
    uint32_t map_bytes;
    uint32_t neighbours_bytes;
    uint32_t crc32;
} iq_codebook_header;
#pragma pack(pop)

typedef struct {
    void *storage;
    void *grid;
    void *map;
    void *neighbours;
} iq_host_codebook;

static_assert(sizeof(int) == 4, "external I-Quant maps require 32-bit int");
static_assert(sizeof(iq_codebook_header) == 28, "unexpected I-Quant codebook header layout");

#ifdef __cplusplus
extern "C" {
#endif

// ============================================================
// Initialization (HIP device + I-Quant lookup tables)
// ============================================================

static bool hip_check(hipError_t e, const char *what) {
    if (e == hipSuccess) return true;
    fprintf(stderr, "hip_quantize: %s failed: %s\n", what, hipGetErrorString(e));
    return false;
}

static void free_iq_tables(void ***ptrs, int count) {
    for (int i = 0; i < count; ++i) {
        if (*ptrs[i]) {
            hipFree(*ptrs[i]);
            *ptrs[i] = NULL;
        }
    }
}

static bool alloc_copy_table(void **dst, const void *src, size_t bytes, const char *name) {
    if (!hip_check(hipMalloc(dst, bytes), name)) return false;
    if (!hip_check(hipMemcpy(*dst, src, bytes, hipMemcpyHostToDevice), name)) {
        hipFree(*dst);
        *dst = NULL;
        return false;
    }
    return true;
}

static uint32_t iq_codebook_crc32(const uint8_t *data, size_t bytes) {
    uint32_t crc = 0xFFFFFFFFu;
    for (size_t i = 0; i < bytes; ++i) {
        crc ^= data[i];
        for (int bit = 0; bit < 8; ++bit) {
            crc = (crc >> 1) ^ (0xEDB88320u & (uint32_t)-(int32_t)(crc & 1u));
        }
    }
    return ~crc;
}

static bool iq_codebook_path(const char *name, char *path, size_t path_size) {
    const char *override_dir = getenv("HIP_QUANT_CODEBOOK_DIR");
    if (override_dir && override_dir[0]) {
        return snprintf(path, path_size, "%s/%s.bin", override_dir, name) > 0;
    }

    char module_path[4096] = {};
#if defined(_WIN32)
    HMODULE module = NULL;
    if (!GetModuleHandleExA(GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS |
                            GET_MODULE_HANDLE_EX_FLAG_UNCHANGED_REFCOUNT,
                            (LPCSTR)&iq_codebook_path, &module)) {
        return false;
    }
    DWORD length = GetModuleFileNameA(module, module_path, (DWORD)sizeof(module_path));
    if (length == 0 || length >= sizeof(module_path)) return false;
#else
    Dl_info module_info = {};
    if (dladdr((void *)&iq_codebook_path, &module_info) == 0 || !module_info.dli_fname) return false;
    if (snprintf(module_path, sizeof(module_path), "%s", module_info.dli_fname) <= 0) return false;
#endif
    char *separator = strrchr(module_path, '/');
#if defined(_WIN32)
    char *backslash = strrchr(module_path, '\\');
    if (!separator || (backslash && backslash > separator)) separator = backslash;
#endif
    if (!separator) return false;
    *separator = '\0';
    return snprintf(path, path_size, "%s/codebooks/%s.bin", module_path, name) > 0;
}

static void free_iq_host_codebook(iq_host_codebook *table) {
    if (table->storage) free(table->storage);
    memset(table, 0, sizeof(*table));
}

static bool load_iq_host_codebook(
    const char *name, size_t grid_bytes, size_t map_bytes, size_t neighbours_bytes,
    iq_host_codebook *table
) {
    static const char expected_magic[8] = {'H', 'Q', 'I', 'Q', 'C', 'B', '0', '1'};
    char path[4096] = {};
    memset(table, 0, sizeof(*table));
    if (!iq_codebook_path(name, path, sizeof(path))) {
        fprintf(stderr, "hip_quantize: could not resolve I-Quant codebook path for %s\n", name);
        return false;
    }

    FILE *file = fopen(path, "rb");
    if (!file) {
        fprintf(stderr, "hip_quantize: missing I-Quant codebook %s (set HIP_QUANT_CODEBOOK_DIR to override)\n", path);
        return false;
    }

    iq_codebook_header header = {};
    const size_t payload_bytes = grid_bytes + map_bytes + neighbours_bytes;
    bool valid = fread(&header, 1, sizeof(header), file) == sizeof(header) &&
        memcmp(header.magic, expected_magic, sizeof(expected_magic)) == 0 &&
        header.version == 1 &&
        header.grid_bytes == grid_bytes &&
        header.map_bytes == map_bytes &&
        header.neighbours_bytes == neighbours_bytes;
    if (valid) {
        if (fseek(file, 0, SEEK_END) != 0 || ftell(file) != (long)(sizeof(header) + payload_bytes) ||
            fseek(file, sizeof(header), SEEK_SET) != 0) {
            valid = false;
        }
    }
    if (!valid) {
        fprintf(stderr, "hip_quantize: invalid I-Quant codebook header in %s\n", path);
        fclose(file);
        return false;
    }

    uint8_t *storage = (uint8_t *)malloc(payload_bytes);
    if (!storage || fread(storage, 1, payload_bytes, file) != payload_bytes ||
        iq_codebook_crc32(storage, payload_bytes) != header.crc32) {
        fprintf(stderr, "hip_quantize: corrupt or unreadable I-Quant codebook %s\n", path);
        if (storage) free(storage);
        fclose(file);
        return false;
    }
    fclose(file);
    table->storage = storage;
    table->grid = storage;
    table->map = storage + grid_bytes;
    table->neighbours = storage + grid_bytes + map_bytes;
    return true;
}

static bool ensure_initialized() {
    if (!hip_initialized) {
        int count = 0;
        if (!hip_check(hipGetDeviceCount(&count), "hipGetDeviceCount")) return false;
        if (count <= 0) {
            fprintf(stderr, "hip_quantize: no HIP devices available\n");
            return false;
        }
        device_id = 0;
        int best_cu = 0;
        for (int i = 0; i < count; i++) {
            hipDeviceProp_t p;
            if (!hip_check(hipGetDeviceProperties(&p, i), "hipGetDeviceProperties")) return false;
            if (p.multiProcessorCount > best_cu) {
                best_cu = p.multiProcessorCount;
                device_id = i;
            }
        }
        if (!hip_check(hipSetDevice(device_id), "hipSetDevice")) return false;
        if (!hip_check(hipGetDeviceProperties(&props, device_id), "hipGetDeviceProperties")) return false;
        hip_initialized = true;
    }
    if (!iq3xxs_tables_loaded) {
        iq_host_codebook table = {};
        if (!load_iq_host_codebook("iq3_xxs", 256 * 4, 4096 * sizeof(int), 22825 * sizeof(uint16_t), &table)) return false;
        bool copied =
            hip_check(hipMemcpyToSymbol(HIP_SYMBOL(d_iq3xxs_grid), table.grid, 256 * 4), "copy iq3xxs grid") &&
            hip_check(hipMemcpyToSymbol(HIP_SYMBOL(d_iq3xxs_map), table.map, 4096 * sizeof(int)), "copy iq3xxs map") &&
            hip_check(hipMemcpyToSymbol(HIP_SYMBOL(d_iq3xxs_neighbours), table.neighbours, 22825 * sizeof(uint16_t)), "copy iq3xxs neighbours");
        free_iq_host_codebook(&table);
        if (!copied) return false;
        iq3xxs_tables_loaded = true;
    }
    if (!iq2xxs_tables_loaded) {
        void **ptrs[] = {(void **)&d_iq2xxs_map_data, (void **)&d_iq2xxs_neighbours_data};
        iq_host_codebook table = {};
        if (!load_iq_host_codebook("iq2_xxs", 256 * 8, 43692 * sizeof(int), 417400 * sizeof(uint16_t), &table)) return false;
        bool copied = hip_check(hipMemcpyToSymbol(HIP_SYMBOL(d_iq2xxs_grid), table.grid, 256 * 8), "copy iq2xxs grid") &&
            alloc_copy_table((void **)&d_iq2xxs_map_data, table.map, 43692 * sizeof(int), "copy iq2xxs map") &&
            alloc_copy_table((void **)&d_iq2xxs_neighbours_data, table.neighbours, 417400 * sizeof(uint16_t), "copy iq2xxs neighbours");
        free_iq_host_codebook(&table);
        if (!copied) { free_iq_tables(ptrs, 2); return false; }
        iq2xxs_tables_loaded = true;
    }
    if (!iq2xs_tables_loaded) {
        void **ptrs[] = {(void **)&d_iq2xs_grid_data, (void **)&d_iq2xs_map_data, (void **)&d_iq2xs_neighbours_data};
        iq_host_codebook table = {};
        if (!load_iq_host_codebook("iq2_xs", 512 * 8, 43692 * sizeof(int), 551722 * sizeof(uint16_t), &table)) return false;
        bool copied =
            alloc_copy_table((void **)&d_iq2xs_grid_data, table.grid, 512 * 8, "copy iq2xs grid") &&
            alloc_copy_table((void **)&d_iq2xs_map_data, table.map, 43692 * sizeof(int), "copy iq2xs map") &&
            alloc_copy_table((void **)&d_iq2xs_neighbours_data, table.neighbours, 551722 * sizeof(uint16_t), "copy iq2xs neighbours");
        free_iq_host_codebook(&table);
        if (!copied) { free_iq_tables(ptrs, 3); return false; }
        iq2xs_tables_loaded = true;
    }
    if (!iq1s_tables_loaded) {
        void **ptrs[] = {(void **)&d_iq1s_grid_data, (void **)&d_iq1s_map_data, (void **)&d_iq1s_neighbours_data};
        iq_host_codebook table = {};
        if (!load_iq_host_codebook("iq1_s", 2048 * 8, 43692 * sizeof(int), 1375339 * sizeof(uint16_t), &table)) return false;
        bool copied =
            alloc_copy_table((void **)&d_iq1s_grid_data, table.grid, 2048 * 8, "copy iq1s grid") &&
            alloc_copy_table((void **)&d_iq1s_map_data, table.map, 43692 * sizeof(int), "copy iq1s map") &&
            alloc_copy_table((void **)&d_iq1s_neighbours_data, table.neighbours, 1375339 * sizeof(uint16_t), "copy iq1s neighbours");
        free_iq_host_codebook(&table);
        if (!copied) { free_iq_tables(ptrs, 3); return false; }
        iq1s_tables_loaded = true;
    }
    if (!iq3s_tables_loaded) {
        void **ptrs[] = {(void **)&d_iq3s_grid_data, (void **)&d_iq3s_map_data, (void **)&d_iq3s_neighbours_data};
        iq_host_codebook table = {};
        if (!load_iq_host_codebook("iq3_s", 512 * 4, 4096 * sizeof(int), 28317 * sizeof(uint16_t), &table)) return false;
        bool copied =
            alloc_copy_table((void **)&d_iq3s_grid_data, table.grid, 512 * 4, "copy iq3s grid") &&
            alloc_copy_table((void **)&d_iq3s_map_data, table.map, 4096 * sizeof(int), "copy iq3s map") &&
            alloc_copy_table((void **)&d_iq3s_neighbours_data, table.neighbours, 28317 * sizeof(uint16_t), "copy iq3s neighbours");
        free_iq_host_codebook(&table);
        if (!copied) { free_iq_tables(ptrs, 3); return false; }
        iq3s_tables_loaded = true;
    }
    return true;
}

// ============================================================
// Size / block helpers
// ============================================================

static size_t get_row_size(int type, int64_t n_per_row) {
    switch (type) {
        case 2:  return sizeof(block_q4_0) * (n_per_row / QK4_0);
        case 3:  return sizeof(block_q4_1) * (n_per_row / QK4_1);
        case 6:  return sizeof(block_q5_0) * (n_per_row / QK5_0);
        case 7:  return sizeof(block_q5_1) * (n_per_row / QK5_1);
        case 8:  return sizeof(block_q8_0) * (n_per_row / QK8_0);
        case 9:  return sizeof(block_q8_1) * (n_per_row / QK8_1);
        case 10: return sizeof(block_q2_K) * (n_per_row / QK_K);
        case 11: return sizeof(block_q3_K) * (n_per_row / QK_K);
        case 12: return sizeof(block_q4_K) * (n_per_row / QK_K);
        case 13: return sizeof(block_q5_K) * (n_per_row / QK_K);
        case 14: return sizeof(block_q6_K) * (n_per_row / QK_K);
        case 16: return sizeof(block_iq2_xxs) * (n_per_row / QK_K);
        case 17: return sizeof(block_iq2_xs) * (n_per_row / QK_K);
        case 18: return sizeof(block_iq3_xxs) * (n_per_row / QK_K);
        case 19: return sizeof(block_iq1_s) * (n_per_row / QK_K);
        case 20: return sizeof(block_iq4_nl) * (n_per_row / QK4_NL);
        case 21: return sizeof(block_iq3_s) * (n_per_row / QK_K);
        case 23: return sizeof(block_iq4_xs) * (n_per_row / QK_K);
        case 38: return sizeof(block_hq2) * (n_per_row / QK_K);
        case 34: return sizeof(block_tq1_0) * (n_per_row / QK_K);
        case 35: return sizeof(block_tq2_0) * (n_per_row / QK_K);
        case 36: return sizeof(block_f8_e4m3) * (n_per_row / QK_F8);
        case 37: return sizeof(block_f8_e5m2) * (n_per_row / QK_F8);
        default: return 0;
    }
}

static int get_blocks_per_row(int type, int64_t n_per_row) {
    switch (type) {
        case 2:  case 3:  case 6:  case 7:  case 8:  case 9:
            return (int)(n_per_row / 32);
        case 10: case 11: case 12: case 13: case 14: case 16: case 17: case 18: case 19: case 21: case 34: case 35: case 38:
            return (int)(n_per_row / QK_K);
        case 20: return (int)(n_per_row / QK4_NL);
        case 23: return (int)(n_per_row / QK_K);
        case 36: case 37: return (int)(n_per_row / QK_F8);
        default: return 0;
    }
}

static bool validate_quant_dims(int64_t nrows, int64_t n_per_row, int n_blocks_per_row) {
    if (nrows <= 0 || n_per_row <= 0 || n_blocks_per_row <= 0) {
        fprintf(stderr, "hip_quantize: dimensions must be positive\n");
        return false;
    }
    if (nrows > INT_MAX || n_per_row > INT_MAX || n_blocks_per_row > INT_MAX) {
        fprintf(stderr, "hip_quantize: dimensions exceed supported int kernel range\n");
        return false;
    }
    if ((uint64_t)nrows > (uint64_t)UINT_MAX || (uint64_t)n_blocks_per_row > (uint64_t)UINT_MAX) {
        fprintf(stderr, "hip_quantize: grid dimensions exceed dim3 range\n");
        return false;
    }
    return true;
}

static bool validate_flat_blocks(int64_t total_elements, int64_t elems_per_block, const char *op) {
    if (total_elements < 0) {
        fprintf(stderr, "hip_quantize: %s element count is negative\n", op);
        return false;
    }
    int64_t blocks = (total_elements + elems_per_block - 1) / elems_per_block;
    if (blocks > (int64_t)INT_MAX) {
        fprintf(stderr, "hip_quantize: %s grid dimension exceeds dim3 range\n", op);
        return false;
    }
    return true;
}

HIP_QUANT_EXPORT size_t ggml_type_size_for(int type) {
    switch (type) {
        case 2:  return sizeof(block_q4_0);
        case 3:  return sizeof(block_q4_1);
        case 6:  return sizeof(block_q5_0);
        case 7:  return sizeof(block_q5_1);
        case 8:  return sizeof(block_q8_0);
        case 9:  return sizeof(block_q8_1);
        case 10: return sizeof(block_q2_K);
        case 11: return sizeof(block_q3_K);
        case 12: return sizeof(block_q4_K);
        case 13: return sizeof(block_q5_K);
        case 14: return sizeof(block_q6_K);
        case 16: return sizeof(block_iq2_xxs);
        case 17: return sizeof(block_iq2_xs);
        case 18: return sizeof(block_iq3_xxs);
        case 19: return sizeof(block_iq1_s);
        case 20: return sizeof(block_iq4_nl);
        case 21: return sizeof(block_iq3_s);
        case 23: return sizeof(block_iq4_xs);
        case 38: return sizeof(block_hq2);
        case 34: return sizeof(block_tq1_0);
        case 35: return sizeof(block_tq2_0);
        case 36: return sizeof(block_f8_e4m3);
        case 37: return sizeof(block_f8_e5m2);
        default: return 0;
    }
}

HIP_QUANT_EXPORT int ggml_blck_size_for(int type) {
    switch (type) {
        case 2:  case 3:  case 6:  case 7:  case 8:  case 9:  return 32;
        case 10: case 11: case 12: case 13: case 14: case 16: case 17: case 18: case 19: case 21: case 34: case 35: case 38: return 256;
        case 20: return QK4_NL;
        case 23: return QK_K;
        case 36: case 37: return QK_F8;
        default: return 0;
    }
}

HIP_QUANT_EXPORT size_t ggml_row_size_for(int type, int64_t n_per_row) {
    int blck = ggml_blck_size_for(type);
    if (blck == 0) return 0;
    return (n_per_row / blck) * ggml_type_size_for(type);
}

HIP_QUANT_EXPORT const char* get_device_name() {
    static thread_local char name[256];
    if (!ensure_initialized()) return "";
    strncpy(name, props.name, 255);
    name[255] = '\0';
    return name;
}

// ============================================================
// Kernel dispatch (shared by quantize_tensor and quantize_tensor_fp8_input)
// ============================================================

static int dispatch_quantize_kernel(
    int type, float *d_src, uint8_t *d_dst, float *d_imatrix,
    int nrows, int n_per_row, int n_blocks_per_row
) {
    dim3 gridDim((unsigned int)nrows, (unsigned int)n_blocks_per_row);

    switch (type) {
        case 2: {
            hipLaunchKernelGGL(quantize_q4_0_kernel, gridDim, 32, 0, 0,
                d_src, d_dst, d_imatrix, nrows, n_per_row);
            break;
        }
        case 3: {
            hipLaunchKernelGGL(quantize_q4_1_kernel, gridDim, 32, 0, 0,
                d_src, d_dst, d_imatrix, nrows, n_per_row);
            break;
        }
        case 6: {
            hipLaunchKernelGGL(quantize_q5_0_kernel, gridDim, 32, 0, 0,
                d_src, d_dst, d_imatrix, nrows, n_per_row);
            break;
        }
        case 7: {
            hipLaunchKernelGGL(quantize_q5_1_kernel, gridDim, 32, 0, 0,
                d_src, d_dst, d_imatrix, nrows, n_per_row);
            break;
        }
        case 8: {
            hipLaunchKernelGGL(quantize_q8_0_kernel, gridDim, 32, 0, 0,
                d_src, d_dst, d_imatrix, nrows, n_per_row);
            break;
        }
        case 9: {
            hipLaunchKernelGGL(quantize_q8_1_kernel, gridDim, 32, 0, 0,
                d_src, d_dst, d_imatrix, nrows, n_per_row);
            break;
        }
        case 10: {
            hipLaunchKernelGGL(quantize_q2_K_kernel, gridDim, 256, 0, 0,
                d_src, d_dst, d_imatrix, nrows, n_per_row);
            break;
        }
        case 11: {
            hipLaunchKernelGGL(quantize_q3_K_kernel, gridDim, 256, 0, 0,
                d_src, d_dst, d_imatrix, nrows, n_per_row);
            break;
        }
        case 12: {
            hipLaunchKernelGGL(quantize_q4_K_kernel, gridDim, 256, 0, 0,
                d_src, d_dst, d_imatrix, nrows, n_per_row);
            break;
        }
        case 13: {
            hipLaunchKernelGGL(quantize_q5_K_kernel, gridDim, 256, 0, 0,
                d_src, d_dst, d_imatrix, nrows, n_per_row);
            break;
        }
        case 14: {
            hipLaunchKernelGGL(quantize_q6_K_kernel, gridDim, 256, 0, 0,
                d_src, d_dst, d_imatrix, nrows, n_per_row);
            break;
        }
        case 16: {
            hipLaunchKernelGGL(quantize_iq2_xxs_kernel, gridDim, 256, 0, 0,
                d_src, d_dst, d_imatrix, d_iq2xxs_map_data, d_iq2xxs_neighbours_data, nrows, n_per_row);
            break;
        }
        case 17: {
            hipLaunchKernelGGL(quantize_iq2_xs_kernel, gridDim, 256, 0, 0,
                d_src, d_dst, d_imatrix, d_iq2xs_grid_data, d_iq2xs_map_data, d_iq2xs_neighbours_data, nrows, n_per_row);
            break;
        }
        case 18: {
            hipLaunchKernelGGL(quantize_iq3_xxs_kernel, gridDim, 256, 0, 0,
                d_src, d_dst, d_imatrix, nrows, n_per_row);
            break;
        }
        case 19: {
            hipLaunchKernelGGL(quantize_iq1_s_kernel, gridDim, 256, 0, 0,
                d_src, d_dst, d_imatrix, d_iq1s_grid_data, d_iq1s_map_data, d_iq1s_neighbours_data, nrows, n_per_row);
            break;
        }
        case 20: {
            hipLaunchKernelGGL(quantize_iq4_nl_kernel, gridDim, QK4_NL, 0, 0,
                d_src, d_dst, d_imatrix, nrows, n_per_row);
            break;
        }
        case 21: {
            hipLaunchKernelGGL(quantize_iq3_s_kernel, gridDim, 256, 0, 0,
                d_src, d_dst, d_imatrix, d_iq3s_grid_data, d_iq3s_map_data, d_iq3s_neighbours_data, nrows, n_per_row);
            break;
        }
        case 23: {
            hipLaunchKernelGGL(quantize_iq4_xs_kernel, gridDim, 256, 0, 0,
                d_src, d_dst, d_imatrix, nrows, n_per_row);
            break;
        }
        case 34: {
            hipLaunchKernelGGL(quantize_tq1_0_kernel, gridDim, 256, 0, 0,
                d_src, d_dst, d_imatrix, nrows, n_per_row);
            break;
        }
        case 35: {
            hipLaunchKernelGGL(quantize_tq2_0_kernel, gridDim, 256, 0, 0,
                d_src, d_dst, d_imatrix, nrows, n_per_row);
            break;
        }
        case 38: {
            hipLaunchKernelGGL(quantize_hq2_kernel, gridDim, 256, 0, 0,
                d_src, d_dst, d_imatrix, nrows, n_per_row);
            break;
        }
        case 36: {
            int64_t total = (int64_t)nrows * n_per_row;
            if (!validate_flat_blocks(total, 256, "quantize_f8_e4m3")) return 0;
            dim3 flatGrid((unsigned int)((total + 255) / 256));
            hipLaunchKernelGGL(quantize_f8_e4m3_kernel, flatGrid, 256, 0, 0,
                d_src, d_dst, d_imatrix, nrows, n_per_row);
            break;
        }
        case 37: {
            int64_t total = (int64_t)nrows * n_per_row;
            if (!validate_flat_blocks(total, 256, "quantize_f8_e5m2")) return 0;
            dim3 flatGrid((unsigned int)((total + 255) / 256));
            hipLaunchKernelGGL(quantize_f8_e5m2_kernel, flatGrid, 256, 0, 0,
                d_src, d_dst, d_imatrix, nrows, n_per_row);
            break;
        }
        default:
            return 0;
    }
    return 1;
}

// ============================================================
// Direct FP8→Quant fused kernel dispatch
//
// Skips the F32 intermediate buffer. Reads FP8 bytes directly.
// Returns 1 if a fused kernel was launched, 0 if this type
// does not have a fused path (caller should fall back).
// ============================================================

static int dispatch_direct_fp8_quant_kernel(
    int type, int src_fp8_type,
    uint8_t *d_src_fp8, uint8_t *d_dst, float *d_imatrix,
    int nrows, int n_per_row, int n_blocks_per_row
) {
    dim3 gridDim((unsigned int)nrows, (unsigned int)n_blocks_per_row);
    dim3 blockDim(32);

    switch (type) {
        case 2:  // Q4_0
            if (src_fp8_type == 37) {
                hipLaunchKernelGGL(quantize_q4_0_from_fp8_e5m2_kernel, gridDim, blockDim, 0, 0,
                    d_src_fp8, d_dst, d_imatrix, nrows, n_per_row);
            } else {
                hipLaunchKernelGGL(quantize_q4_0_from_fp8_e4m3_kernel, gridDim, blockDim, 0, 0,
                    d_src_fp8, d_dst, d_imatrix, nrows, n_per_row);
            }
            break;
        case 3:  // Q4_1
            if (src_fp8_type == 37) {
                hipLaunchKernelGGL(quantize_q4_1_from_fp8_e5m2_kernel, gridDim, blockDim, 0, 0,
                    d_src_fp8, d_dst, d_imatrix, nrows, n_per_row);
            } else {
                hipLaunchKernelGGL(quantize_q4_1_from_fp8_e4m3_kernel, gridDim, blockDim, 0, 0,
                    d_src_fp8, d_dst, d_imatrix, nrows, n_per_row);
            }
            break;
        case 6:  // Q5_0
            if (src_fp8_type == 37) {
                hipLaunchKernelGGL(quantize_q5_0_from_fp8_e5m2_kernel, gridDim, blockDim, 0, 0,
                    d_src_fp8, d_dst, d_imatrix, nrows, n_per_row);
            } else {
                hipLaunchKernelGGL(quantize_q5_0_from_fp8_e4m3_kernel, gridDim, blockDim, 0, 0,
                    d_src_fp8, d_dst, d_imatrix, nrows, n_per_row);
            }
            break;
        case 7:  // Q5_1
            if (src_fp8_type == 37) {
                hipLaunchKernelGGL(quantize_q5_1_from_fp8_e5m2_kernel, gridDim, blockDim, 0, 0,
                    d_src_fp8, d_dst, d_imatrix, nrows, n_per_row);
            } else {
                hipLaunchKernelGGL(quantize_q5_1_from_fp8_e4m3_kernel, gridDim, blockDim, 0, 0,
                    d_src_fp8, d_dst, d_imatrix, nrows, n_per_row);
            }
            break;
        case 8:  // Q8_0
            if (src_fp8_type == 37) {
                hipLaunchKernelGGL(quantize_q8_0_from_fp8_e5m2_kernel, gridDim, blockDim, 0, 0,
                    d_src_fp8, d_dst, d_imatrix, nrows, n_per_row);
            } else {
                hipLaunchKernelGGL(quantize_q8_0_from_fp8_e4m3_kernel, gridDim, blockDim, 0, 0,
                    d_src_fp8, d_dst, d_imatrix, nrows, n_per_row);
            }
            break;
        case 9:  // Q8_1
            if (src_fp8_type == 37) {
                hipLaunchKernelGGL(quantize_q8_1_from_fp8_e5m2_kernel, gridDim, blockDim, 0, 0,
                    d_src_fp8, d_dst, d_imatrix, nrows, n_per_row);
            } else {
                hipLaunchKernelGGL(quantize_q8_1_from_fp8_e4m3_kernel, gridDim, blockDim, 0, 0,
                    d_src_fp8, d_dst, d_imatrix, nrows, n_per_row);
            }
            break;
        default:
            return 0;  // no fused kernel for this type
    }
    return 1;
}

// ============================================================
// Q-type -> FP8 kernel dispatch
// ============================================================

#ifdef __cplusplus
extern "C++" {
#endif
template <bool E5M2>
static int dispatch_dequantize_to_fp8_kernel(
    int type, const uint8_t *d_src, uint8_t *d_dst,
    int nrows, int n_per_row, int n_blocks_per_row
) {
    // AMD GPUs cap gridDim.x at 65535. Spread additional rows over z while
    // keeping the row-major public API and the existing x/y block mapping.
    const unsigned int row_grid = (unsigned int)((nrows < 65535) ? nrows : 65535);
    const unsigned int row_layers = ((unsigned int)nrows + row_grid - 1u) / row_grid;
    dim3 gridDim(row_grid, (unsigned int)n_blocks_per_row, row_layers);

    switch (type) {
        case 2:
            hipLaunchKernelGGL(HIP_KERNEL_NAME(dequant_q4_0_to_fp8_kernel<E5M2>), gridDim, 32, 0, 0,
                (const block_q4_0 *)d_src, d_dst, nrows, n_blocks_per_row, n_per_row);
            break;
        case 3:
            hipLaunchKernelGGL(HIP_KERNEL_NAME(dequant_q4_1_to_fp8_kernel<E5M2>), gridDim, 32, 0, 0,
                (const block_q4_1 *)d_src, d_dst, nrows, n_blocks_per_row, n_per_row);
            break;
        case 6:
            hipLaunchKernelGGL(HIP_KERNEL_NAME(dequant_q5_0_to_fp8_kernel<E5M2>), gridDim, 32, 0, 0,
                (const block_q5_0 *)d_src, d_dst, nrows, n_blocks_per_row, n_per_row);
            break;
        case 7:
            hipLaunchKernelGGL(HIP_KERNEL_NAME(dequant_q5_1_to_fp8_kernel<E5M2>), gridDim, 32, 0, 0,
                (const block_q5_1 *)d_src, d_dst, nrows, n_blocks_per_row, n_per_row);
            break;
        case 8:
            hipLaunchKernelGGL(HIP_KERNEL_NAME(dequant_q8_0_to_fp8_kernel<E5M2>), gridDim, 32, 0, 0,
                (const block_q8_0 *)d_src, d_dst, nrows, n_blocks_per_row, n_per_row);
            break;
        case 9:
            hipLaunchKernelGGL(HIP_KERNEL_NAME(dequant_q8_1_to_fp8_kernel<E5M2>), gridDim, 32, 0, 0,
                (const block_q8_1 *)d_src, d_dst, nrows, n_blocks_per_row, n_per_row);
            break;
        case 10:
            hipLaunchKernelGGL(HIP_KERNEL_NAME(dequant_q2_k_to_fp8_kernel<E5M2>), gridDim, 256, 0, 0,
                (const block_q2_K *)d_src, d_dst, nrows, n_blocks_per_row, n_per_row);
            break;
        case 11:
            hipLaunchKernelGGL(HIP_KERNEL_NAME(dequant_q3_k_to_fp8_kernel<E5M2>), gridDim, 256, 0, 0,
                (const block_q3_K *)d_src, d_dst, nrows, n_blocks_per_row, n_per_row);
            break;
        case 12:
            hipLaunchKernelGGL(HIP_KERNEL_NAME(dequant_q4_k_to_fp8_kernel<E5M2>), gridDim, 256, 0, 0,
                (const block_q4_K *)d_src, d_dst, nrows, n_blocks_per_row, n_per_row);
            break;
        case 13:
            hipLaunchKernelGGL(HIP_KERNEL_NAME(dequant_q5_k_to_fp8_kernel<E5M2>), gridDim, 256, 0, 0,
                (const block_q5_K *)d_src, d_dst, nrows, n_blocks_per_row, n_per_row);
            break;
        case 14:
            hipLaunchKernelGGL(HIP_KERNEL_NAME(dequant_q6_k_to_fp8_kernel<E5M2>), gridDim, 256, 0, 0,
                (const block_q6_K *)d_src, d_dst, nrows, n_blocks_per_row, n_per_row);
            break;
        case 16:
            hipLaunchKernelGGL(HIP_KERNEL_NAME(dequant_iq2_xxs_to_fp8_kernel<E5M2>), gridDim, 256, 0, 0,
                (const block_iq2_xxs *)d_src, d_dst, nrows, n_blocks_per_row, n_per_row);
            break;
        case 17:
            hipLaunchKernelGGL(HIP_KERNEL_NAME(dequant_iq2_xs_to_fp8_kernel<E5M2>), gridDim, 256, 0, 0,
                (const block_iq2_xs *)d_src, d_dst, d_iq2xs_grid_data, nrows, n_blocks_per_row, n_per_row);
            break;
        case 18:
            hipLaunchKernelGGL(HIP_KERNEL_NAME(dequant_iq3_xxs_to_fp8_kernel<E5M2>), gridDim, 256, 0, 0,
                (const block_iq3_xxs *)d_src, d_dst, nrows, n_blocks_per_row, n_per_row);
            break;
        case 19:
            hipLaunchKernelGGL(HIP_KERNEL_NAME(dequant_iq1_s_to_fp8_kernel<E5M2>), gridDim, 256, 0, 0,
                (const block_iq1_s *)d_src, d_dst, d_iq1s_grid_data, nrows, n_blocks_per_row, n_per_row);
            break;
        case 20:
            hipLaunchKernelGGL(HIP_KERNEL_NAME(dequant_iq4_nl_to_fp8_kernel<E5M2>), gridDim, 32, 0, 0,
                (const block_iq4_nl *)d_src, d_dst, nrows, n_blocks_per_row, n_per_row);
            break;
        case 21:
            hipLaunchKernelGGL(HIP_KERNEL_NAME(dequant_iq3_s_to_fp8_kernel<E5M2>), gridDim, 256, 0, 0,
                (const block_iq3_s *)d_src, d_dst, d_iq3s_grid_data, nrows, n_blocks_per_row, n_per_row);
            break;
        case 23:
            hipLaunchKernelGGL(HIP_KERNEL_NAME(dequant_iq4_xs_to_fp8_kernel<E5M2>), gridDim, 256, 0, 0,
                (const block_iq4_xs *)d_src, d_dst, nrows, n_blocks_per_row, n_per_row);
            break;
        case 34:
            hipLaunchKernelGGL(HIP_KERNEL_NAME(dequant_tq1_0_to_fp8_kernel<E5M2>), gridDim, 256, 0, 0,
                (const block_tq1_0 *)d_src, d_dst, nrows, n_blocks_per_row, n_per_row);
            break;
        case 35:
            hipLaunchKernelGGL(HIP_KERNEL_NAME(dequant_tq2_0_to_fp8_kernel<E5M2>), gridDim, 256, 0, 0,
                (const block_tq2_0 *)d_src, d_dst, nrows, n_blocks_per_row, n_per_row);
            break;
        case 38:
            hipLaunchKernelGGL(HIP_KERNEL_NAME(dequant_hq2_to_fp8_kernel<E5M2>), gridDim, 256, 0, 0,
                (const block_hq2 *)d_src, d_dst, nrows, n_blocks_per_row, n_per_row);
            break;
        default:
            return 0;
    }
    return 1;
}
#ifdef __cplusplus
}
#endif

// ============================================================
// quantize_tensor — standard F32 input path
// ============================================================

HIP_QUANT_EXPORT size_t quantize_tensor(
    int type,
    const float* src,
    uint8_t* dst,
    int64_t nrows,
    int64_t n_per_row,
    const float* imatrix
) {
    if (!ensure_initialized()) return 0;

    int n_blocks_per_row = get_blocks_per_row(type, n_per_row);
    if (!validate_quant_dims(nrows, n_per_row, n_blocks_per_row)) return 0;

    size_t row_size = get_row_size(type, n_per_row);
    if (row_size == 0) {
        fprintf(stderr, "hip_quantize: unsupported type %d\n", type);
        return 0;
    }
    size_t total_size = row_size * nrows;
    if (total_size == 0) return 0;

    size_t src_bytes = (size_t)nrows * n_per_row * sizeof(float);
    size_t dst_bytes = total_size;
    size_t imatrix_bytes = imatrix ? src_bytes : 0;

    if (src_bytes > g_d_src_cap) {
        if (g_d_src) hipFree(g_d_src);
        hipError_t e = hipMalloc(&g_d_src, src_bytes);
        if (e != hipSuccess) { fprintf(stderr, "hip_quantize: hipMalloc(d_src, %zu) failed: %s\n", src_bytes, hipGetErrorString(e)); return 0; }
        g_d_src_cap = src_bytes;
    }
    if (dst_bytes > g_d_dst_cap) {
        if (g_d_dst) hipFree(g_d_dst);
        hipError_t e = hipMalloc(&g_d_dst, dst_bytes);
        if (e != hipSuccess) { fprintf(stderr, "hip_quantize: hipMalloc(d_dst, %zu) failed: %s\n", dst_bytes, hipGetErrorString(e)); return 0; }
        g_d_dst_cap = dst_bytes;
    }
    if (imatrix_bytes > g_d_imatrix_cap) {
        if (g_d_imatrix) hipFree(g_d_imatrix);
        hipError_t e = hipMalloc(&g_d_imatrix, imatrix_bytes);
        if (e != hipSuccess) { fprintf(stderr, "hip_quantize: hipMalloc(d_imatrix) failed: %s\n", hipGetErrorString(e)); return 0; }
        g_d_imatrix_cap = imatrix_bytes;
    }

    {
        hipError_t e = hipMemcpy(g_d_src, src, src_bytes, hipMemcpyHostToDevice);
        if (e != hipSuccess) { fprintf(stderr, "hip_quantize: hipMemcpy(d_src) failed: %s\n", hipGetErrorString(e)); return 0; }
    }
    if (imatrix) {
        hipError_t e = hipMemcpy(g_d_imatrix, imatrix, imatrix_bytes, hipMemcpyHostToDevice);
        if (e != hipSuccess) { fprintf(stderr, "hip_quantize: hipMemcpy(d_imatrix) failed: %s\n", hipGetErrorString(e)); return 0; }
    }
    {
        hipError_t e = hipMemset(g_d_dst, 0, dst_bytes);
        if (e != hipSuccess) { fprintf(stderr, "hip_quantize: hipMemset failed: %s\n", hipGetErrorString(e)); return 0; }
    }

    if (!dispatch_quantize_kernel(type, g_d_src, g_d_dst, imatrix ? g_d_imatrix : NULL, (int)nrows, (int)n_per_row, n_blocks_per_row)) {
        return 0;
    }

    hipError_t err = hipGetLastError();
    if (err != hipSuccess) {
        fprintf(stderr, "hip_quantize: kernel launch error: %s (code %d)\n", hipGetErrorString(err), (int)err);
        return 0;
    }

    {
        hipError_t e = hipDeviceSynchronize();
        if (e != hipSuccess) { fprintf(stderr, "hip_quantize: hipDeviceSynchronize failed: %s\n", hipGetErrorString(e)); return 0; }
    }

    {
        hipError_t e = hipMemcpy(dst, g_d_dst, dst_bytes, hipMemcpyDeviceToHost);
        if (e != hipSuccess) { fprintf(stderr, "hip_quantize: hipMemcpy(dst) failed: %s\n", hipGetErrorString(e)); return 0; }
    }

    return total_size;
}

// ============================================================
// quantize_tensor_fp8_input_impl — FP8 input path
//
// Accepts FP8 source data (1 byte per element) instead of float32
// (4 bytes). Matching FP8 output types are copied directly; other targets
// upload to GPU and expand to float32 on-device before quantizing.
//
// Benefits:
//   - Host memory: 4x less than F32, 2x less than BF16
//   - Transfer bandwidth: 4x less than F32
//
// Quality note: FP8 E4M3 has ~3 bits of mantissa precision.
// This is fine for low-bit targets (Q4_0 through Q5_K) where
// quantization noise dominates. For Q8_0+ and I-Quants, prefer
// the standard F32 input path.
// ============================================================

static size_t quantize_tensor_fp8_input_impl(
    int type,
    const uint8_t* src_fp8,
    uint8_t* dst,
    int64_t nrows,
    int64_t n_per_row,
    const float* imatrix,
    int src_fp8_type
) {
    if (!ensure_initialized()) return 0;

    int n_blocks_per_row = get_blocks_per_row(type, n_per_row);
    if (!validate_quant_dims(nrows, n_per_row, n_blocks_per_row)) return 0;

    size_t row_size = get_row_size(type, n_per_row);
    if (row_size == 0) {
        fprintf(stderr, "hip_quantize: unsupported type %d\n", type);
        return 0;
    }
    size_t total_size = row_size * nrows;
    if (total_size == 0) return 0;

    int64_t total_elements = nrows * n_per_row;
    if (!validate_flat_blocks(total_elements, 256, "fp8 expand")) return 0;

    if (type == src_fp8_type && (type == 36 || type == 37)) {
        memcpy(dst, src_fp8, (size_t)total_elements);
        return total_size;
    }

    // === Phase 1: Upload FP8 source (1 byte per element) ===
    size_t src_fp8_bytes = (size_t)total_elements;
    if (src_fp8_bytes > g_d_src_fp8_cap) {
        if (g_d_src_fp8) hipFree(g_d_src_fp8);
        hipError_t e = hipMalloc(&g_d_src_fp8, src_fp8_bytes);
        if (e != hipSuccess) { fprintf(stderr, "hip_quantize: hipMalloc(d_src_fp8) failed: %s\n", hipGetErrorString(e)); return 0; }
        g_d_src_fp8_cap = src_fp8_bytes;
    }
    {
        hipError_t e = hipMemcpy(g_d_src_fp8, src_fp8, src_fp8_bytes, hipMemcpyHostToDevice);
        if (e != hipSuccess) { fprintf(stderr, "hip_quantize: hipMemcpy(d_src_fp8) failed: %s\n", hipGetErrorString(e)); return 0; }
    }

    // === Fused path: try direct FP8→Quant kernel (no intermediate F32) ===
    {
        size_t dst_bytes = total_size;
        if (dst_bytes > g_d_dst_cap) {
            if (g_d_dst) hipFree(g_d_dst);
            hipError_t e = hipMalloc(&g_d_dst, dst_bytes);
            if (e != hipSuccess) { fprintf(stderr, "hip_quantize: hipMalloc(d_dst) failed: %s\n", hipGetErrorString(e)); return 0; }
            g_d_dst_cap = dst_bytes;
        }
        if (imatrix) {
            size_t imatrix_bytes = (size_t)total_elements * sizeof(float);
            if (imatrix_bytes > g_d_imatrix_cap) {
                if (g_d_imatrix) hipFree(g_d_imatrix);
                hipError_t e = hipMalloc(&g_d_imatrix, imatrix_bytes);
                if (e != hipSuccess) { fprintf(stderr, "hip_quantize: hipMalloc(d_imatrix) failed: %s\n", hipGetErrorString(e)); return 0; }
                g_d_imatrix_cap = imatrix_bytes;
            }
            hipError_t e = hipMemcpy(g_d_imatrix, imatrix, imatrix_bytes, hipMemcpyHostToDevice);
            if (e != hipSuccess) { fprintf(stderr, "hip_quantize: hipMemcpy(d_imatrix) failed: %s\n", hipGetErrorString(e)); return 0; }
        }
        {
            hipError_t e = hipMemset(g_d_dst, 0, dst_bytes);
            if (e != hipSuccess) { fprintf(stderr, "hip_quantize: hipMemset failed: %s\n", hipGetErrorString(e)); return 0; }
        }
        if (dispatch_direct_fp8_quant_kernel(type, src_fp8_type,
                g_d_src_fp8, g_d_dst, imatrix ? g_d_imatrix : NULL,
                (int)nrows, (int)n_per_row, n_blocks_per_row)) {
            hipError_t err = hipGetLastError();
            if (err != hipSuccess) {
                fprintf(stderr, "hip_quantize: fused kernel error: %s\n", hipGetErrorString(err));
                return 0;
            }
            hipDeviceSynchronize();
            hipMemcpy(dst, g_d_dst, dst_bytes, hipMemcpyDeviceToHost);
            return total_size;
        }
    }

    // === Fallback: Phase 2 — Expand FP8 -> F32 on device ===
    size_t src_f32_bytes = (size_t)total_elements * sizeof(float);
    if (src_f32_bytes > g_d_src_cap) {
        if (g_d_src) hipFree(g_d_src);
        hipError_t e = hipMalloc(&g_d_src, src_f32_bytes);
        if (e != hipSuccess) { fprintf(stderr, "hip_quantize: hipMalloc(d_src f32) failed: %s\n", hipGetErrorString(e)); return 0; }
        g_d_src_cap = src_f32_bytes;
    }
    {
        int threads = 256;
        int blocks = (int)((total_elements + threads - 1) / threads);
        if (src_fp8_type == 37) {
            hipLaunchKernelGGL(fp8_e5m2_to_f32_expand_kernel, dim3(blocks), dim3(threads), 0, 0,
                g_d_src_fp8, g_d_src, total_elements);
        } else {
            hipLaunchKernelGGL(fp8_to_f32_expand_kernel, dim3(blocks), dim3(threads), 0, 0,
                g_d_src_fp8, g_d_src, total_elements);
        }
        hipError_t e = hipGetLastError();
        if (e != hipSuccess) {
            fprintf(stderr, "hip_quantize: fp8_expand kernel error: %s\n", hipGetErrorString(e));
            return 0;
        }
    }

    // === Phase 3: Allocate output + imatrix, dispatch quantize kernel ===
    size_t dst_bytes = total_size;

    if (dst_bytes > g_d_dst_cap) {
        if (g_d_dst) hipFree(g_d_dst);
        hipError_t e = hipMalloc(&g_d_dst, dst_bytes);
        if (e != hipSuccess) { fprintf(stderr, "hip_quantize: hipMalloc(d_dst) failed: %s\n", hipGetErrorString(e)); return 0; }
        g_d_dst_cap = dst_bytes;
    }
    if (imatrix) {
        size_t imatrix_bytes = (size_t)total_elements * sizeof(float);
        if (imatrix_bytes > g_d_imatrix_cap) {
            if (g_d_imatrix) hipFree(g_d_imatrix);
            hipError_t e = hipMalloc(&g_d_imatrix, imatrix_bytes);
            if (e != hipSuccess) { fprintf(stderr, "hip_quantize: hipMalloc(d_imatrix) failed: %s\n", hipGetErrorString(e)); return 0; }
            g_d_imatrix_cap = imatrix_bytes;
        }
        hipError_t e = hipMemcpy(g_d_imatrix, imatrix, imatrix_bytes, hipMemcpyHostToDevice);
        if (e != hipSuccess) { fprintf(stderr, "hip_quantize: hipMemcpy(d_imatrix) failed: %s\n", hipGetErrorString(e)); return 0; }
    }
    {
        hipError_t e = hipMemset(g_d_dst, 0, dst_bytes);
        if (e != hipSuccess) { fprintf(stderr, "hip_quantize: hipMemset failed: %s\n", hipGetErrorString(e)); return 0; }
    }

    if (!dispatch_quantize_kernel(type, g_d_src, g_d_dst, imatrix ? g_d_imatrix : NULL, (int)nrows, (int)n_per_row, n_blocks_per_row)) {
        return 0;
    }

    hipError_t err = hipGetLastError();
    if (err != hipSuccess) {
        fprintf(stderr, "hip_quantize: kernel launch error: %s (code %d)\n", hipGetErrorString(err), (int)err);
        return 0;
    }

    {
        hipError_t e = hipDeviceSynchronize();
        if (e != hipSuccess) { fprintf(stderr, "hip_quantize: hipDeviceSynchronize failed: %s\n", hipGetErrorString(e)); return 0; }
    }

    {
        hipError_t e = hipMemcpy(dst, g_d_dst, dst_bytes, hipMemcpyDeviceToHost);
        if (e != hipSuccess) { fprintf(stderr, "hip_quantize: hipMemcpy(dst) failed: %s\n", hipGetErrorString(e)); return 0; }
    }

    return total_size;
}

HIP_QUANT_EXPORT size_t quantize_tensor_fp8_input(
    int type,
    const uint8_t* src_fp8,
    uint8_t* dst,
    int64_t nrows,
    int64_t n_per_row,
    const float* imatrix
) {
    return quantize_tensor_fp8_input_impl(type, src_fp8, dst, nrows, n_per_row, imatrix, 36);
}

HIP_QUANT_EXPORT size_t quantize_tensor_fp8_e5m2_input(
    int type,
    const uint8_t* src_fp8,
    uint8_t* dst,
    int64_t nrows,
    int64_t n_per_row,
    const float* imatrix
) {
    return quantize_tensor_fp8_input_impl(type, src_fp8, dst, nrows, n_per_row, imatrix, 37);
}

// ============================================================
// quantize_tensor_fp8_e5m2_stochastic — stochastic E5M2
// ============================================================

HIP_QUANT_EXPORT size_t quantize_tensor_fp8_e5m2_stochastic(
    const float* src,
    uint8_t* dst,
    int64_t nrows,
    int64_t n_per_row,
    uint64_t seed
) {
    if (!ensure_initialized()) return 0;

    int64_t total_elements = nrows * n_per_row;
    if (!validate_flat_blocks(total_elements, 256, "stochastic E5M2")) return 0;

    size_t src_bytes = (size_t)total_elements * sizeof(float);
    size_t dst_bytes = (size_t)total_elements;

    if (src_bytes > g_d_src_cap) {
        if (g_d_src) hipFree(g_d_src);
        hipError_t e = hipMalloc(&g_d_src, src_bytes);
        if (e != hipSuccess) { fprintf(stderr, "hip_quantize: stochastic E5M2 malloc failed\n"); return 0; }
        g_d_src_cap = src_bytes;
    }
    if (dst_bytes > g_d_dst_cap) {
        if (g_d_dst) hipFree(g_d_dst);
        hipError_t e = hipMalloc(&g_d_dst, dst_bytes);
        if (e != hipSuccess) { fprintf(stderr, "hip_quantize: stochastic E5M2 malloc failed\n"); return 0; }
        g_d_dst_cap = dst_bytes;
    }

    hipMemcpy(g_d_src, src, src_bytes, hipMemcpyHostToDevice);

    dim3 grid((unsigned int)((total_elements + 255) / 256));
    hipLaunchKernelGGL(quantize_f8_e5m2_stochastic_kernel, grid, 256, 0, 0,
        g_d_src, g_d_dst, nrows, n_per_row, seed);

    hipError_t err = hipGetLastError();
    if (err != hipSuccess) {
        fprintf(stderr, "hip_quantize: stochastic E5M2 kernel error: %s\n", hipGetErrorString(err));
        return 0;
    }
    hipDeviceSynchronize();
    hipMemcpy(dst, g_d_dst, dst_bytes, hipMemcpyDeviceToHost);
    return dst_bytes;
}

// ============================================================
// dequantize_tensor_to_fp8 — packed GGML Q input path
//
// Expands Q4/Q5/Q8 and K-quant blocks directly to raw FP8 E4M3 or E5M2
// bytes.  The intermediate float value exists only in a GPU register, so the
// conversion does not allocate or transfer an F32 tensor.
// ============================================================

HIP_QUANT_EXPORT size_t dequantize_tensor_to_fp8(
    int type,
    const uint8_t* src,
    uint8_t* dst_fp8,
    int64_t nrows,
    int64_t n_per_row,
    int dst_fp8_type
) {
    if (dst_fp8_type != 36 && dst_fp8_type != 37) {
        fprintf(stderr, "hip_quantize: FP8 destination type must be F8_E4M3 (36) or F8_E5M2 (37)\n");
        return 0;
    }
    if (!ensure_initialized()) return 0;

    int n_blocks_per_row = get_blocks_per_row(type, n_per_row);
    if (!validate_quant_dims(nrows, n_per_row, n_blocks_per_row)) return 0;

    size_t row_size = get_row_size(type, n_per_row);
    if (row_size == 0) {
        fprintf(stderr, "hip_quantize: unsupported type %d\n", type);
        return 0;
    }
    const int64_t total_elements = nrows * n_per_row;
    if (!validate_flat_blocks(total_elements, 256, "Q to FP8 dequantize")) return 0;

    // A matching FP8 source is already the requested output representation.
    if (type == dst_fp8_type) {
        memcpy(dst_fp8, src, (size_t)total_elements);
        return (size_t)total_elements;
    }

    const size_t src_bytes = row_size * (size_t)nrows;
    const size_t dst_bytes = (size_t)total_elements;
    if (src_bytes > g_d_dst_cap) {
        if (g_d_dst) hipFree(g_d_dst);
        hipError_t e = hipMalloc(&g_d_dst, src_bytes);
        if (e != hipSuccess) { fprintf(stderr, "hip_quantize: hipMalloc(Q source) failed: %s\n", hipGetErrorString(e)); return 0; }
        g_d_dst_cap = src_bytes;
    }
    if (dst_bytes > g_d_src_fp8_cap) {
        if (g_d_src_fp8) hipFree(g_d_src_fp8);
        hipError_t e = hipMalloc(&g_d_src_fp8, dst_bytes);
        if (e != hipSuccess) { fprintf(stderr, "hip_quantize: hipMalloc(FP8 destination) failed: %s\n", hipGetErrorString(e)); return 0; }
        g_d_src_fp8_cap = dst_bytes;
    }

    {
        hipError_t e = hipMemcpy(g_d_dst, src, src_bytes, hipMemcpyHostToDevice);
        if (e != hipSuccess) { fprintf(stderr, "hip_quantize: hipMemcpy(Q source) failed: %s\n", hipGetErrorString(e)); return 0; }
    }

    const bool launched = dst_fp8_type == 37
        ? dispatch_dequantize_to_fp8_kernel<true>(type, g_d_dst, g_d_src_fp8,
                                                   (int)nrows, (int)n_per_row, n_blocks_per_row)
        : dispatch_dequantize_to_fp8_kernel<false>(type, g_d_dst, g_d_src_fp8,
                                                    (int)nrows, (int)n_per_row, n_blocks_per_row);
    if (!launched) {
        fprintf(stderr,
            "hip_quantize: Q to FP8 dequantization supports all Q4/Q5/Q8, K-Quant, I-Quant, T-Quant, and IQ4_NL types; type %d is not supported\n",
            type);
        return 0;
    }

    hipError_t err = hipGetLastError();
    if (err != hipSuccess) {
        fprintf(stderr, "hip_quantize: Q to FP8 kernel launch error: %s (code %d)\n", hipGetErrorString(err), (int)err);
        return 0;
    }
    {
        hipError_t e = hipDeviceSynchronize();
        if (e != hipSuccess) { fprintf(stderr, "hip_quantize: Q to FP8 synchronize failed: %s\n", hipGetErrorString(e)); return 0; }
    }
    {
        hipError_t e = hipMemcpy(dst_fp8, g_d_src_fp8, dst_bytes, hipMemcpyDeviceToHost);
        if (e != hipSuccess) { fprintf(stderr, "hip_quantize: hipMemcpy(FP8 destination) failed: %s\n", hipGetErrorString(e)); return 0; }
    }
    return dst_bytes;
}

// ============================================================
// fp8_gemm_test — Micro FP8 GEMM via rocWMMA WMMA
//
// Takes pre-quantized FP8 E4M3 matrices A (MxK) and B (KxN),
// computes C = A * B using rocWMMA WMMA fragments on gfx12.
// Returns float32 C in pre-allocated host buffer.
//
// All matrices are row-major. lda >= K, ldb >= N, ldc >= N.
// M, N must be multiples of 16; K can be any positive int.
// ============================================================

HIP_QUANT_EXPORT int fp8_gemm_test_wmma(
    const uint8_t* A_fp8,
    const uint8_t* B_fp8,
    float* C,
    int M,
    int N,
    int K,
    int lda,
    int ldb,
    int ldc
) {
    if (!ensure_initialized()) return 1;

    if (M <= 0 || N <= 0 || K <= 0 || lda < K || ldb < N || ldc < N || (M % 16) != 0 || (N % 16) != 0) {
        fprintf(stderr, "fp8_gemm: invalid dimensions or leading dimensions\n");
        return 1;
    }

    const char *disable_wmma = getenv("HIP_QUANT_DISABLE_WMMA");
    if (disable_wmma != NULL && (
        strcmp(disable_wmma, "1") == 0 || strcmp(disable_wmma, "true") == 0 ||
        strcmp(disable_wmma, "yes") == 0 || strcmp(disable_wmma, "on") == 0
    )) {
        fprintf(stderr, "fp8_gemm: disabled by HIP_QUANT_DISABLE_WMMA\n");
        return 4;
    }

    if (strstr(props.gcnArchName, "gfx12") == NULL) {
        fprintf(stderr, "fp8_gemm: this FP8 WMMA kernel uses gfx12/RDNA4 w32 intrinsics; current arch is %s\n", props.gcnArchName);
        return 2;
    }

    int runtime_version = 0;
    hipRuntimeGetVersion(&runtime_version);
    if (runtime_version > 0 && runtime_version < 70200000) {
        fprintf(stderr, "fp8_gemm: gfx12 FP8 WMMA requires ROCm/HIP 7.2+; current runtime is %d\n", runtime_version);
        return 3;
    }

    size_t bytes_A = (size_t)M * lda;
    size_t bytes_B = (size_t)K * ldb;
    size_t bytes_C = (size_t)M * ldc * sizeof(float);

    uint8_t *d_A = NULL, *d_B = NULL;
    float *d_C = NULL;

    hipError_t e;

    e = hipMalloc(&d_A, bytes_A);
    if (e != hipSuccess) { fprintf(stderr, "fp8_gemm: hipMalloc A failed: %s\n", hipGetErrorString(e)); return 1; }
    e = hipMalloc(&d_B, bytes_B);
    if (e != hipSuccess) { fprintf(stderr, "fp8_gemm: hipMalloc B failed: %s\n", hipGetErrorString(e)); hipFree(d_A); return 1; }
    e = hipMalloc(&d_C, bytes_C);
    if (e != hipSuccess) { fprintf(stderr, "fp8_gemm: hipMalloc C failed: %s\n", hipGetErrorString(e)); hipFree(d_A); hipFree(d_B); return 1; }

    e = hipMemcpy(d_A, A_fp8, bytes_A, hipMemcpyHostToDevice);
    if (e != hipSuccess) { fprintf(stderr, "fp8_gemm: hipMemcpy A failed: %s\n", hipGetErrorString(e)); hipFree(d_A); hipFree(d_B); hipFree(d_C); return 1; }
    e = hipMemcpy(d_B, B_fp8, bytes_B, hipMemcpyHostToDevice);
    if (e != hipSuccess) { fprintf(stderr, "fp8_gemm: hipMemcpy B failed: %s\n", hipGetErrorString(e)); hipFree(d_A); hipFree(d_B); hipFree(d_C); return 1; }

    dim3 gridDim((M + 15) / 16, (N + 15) / 16);
    hipLaunchKernelGGL(fp8_gemm_wmma_kernel, gridDim, 32, 0, 0,
        d_A, d_B, d_C, M, N, K, lda, ldb, ldc);

    e = hipGetLastError();
    if (e != hipSuccess) { fprintf(stderr, "fp8_gemm: kernel launch error: %s\n", hipGetErrorString(e)); hipFree(d_A); hipFree(d_B); hipFree(d_C); return 1; }

    e = hipDeviceSynchronize();
    if (e != hipSuccess) { fprintf(stderr, "fp8_gemm: sync error: %s\n", hipGetErrorString(e)); hipFree(d_A); hipFree(d_B); hipFree(d_C); return 1; }

    e = hipMemcpy(C, d_C, bytes_C, hipMemcpyDeviceToHost);
    if (e != hipSuccess) { fprintf(stderr, "fp8_gemm: hipMemcpy C failed: %s\n", hipGetErrorString(e)); hipFree(d_A); hipFree(d_B); hipFree(d_C); return 1; }

    hipFree(d_A); hipFree(d_B); hipFree(d_C);
    return 0;
}

// ============================================================
// wmma_diag — WMMA stability diagnostic
//
// Runs four WMMA kernel tests to determine whether the
// __builtin_amdgcn_wmma_f32_16x16x16_fp8_fp8_w32_gfx12
// intrinsic is functioning correctly (no hangs, no zero outputs).
//
// Returns a 4-element int array via host pointer:
//   ret[0] = Test 1: max output value (should be ~K when inputs=1.0)
//   ret[1] = Test 2: OK flag (0 = pass, negative = failed at iteration |ret[1]|)
//   ret[2] = Test 3: max output value from LDS-staged WMMA
//   ret[3] = Test 4: number of waves that produced non-zero output (0-16)
//
// Returns 0 on success, non-zero on HIP runtime error.
// ============================================================

static int wmma_diag_check_gating() {
    const char *disable_wmma = getenv("HIP_QUANT_DISABLE_WMMA");
    if (disable_wmma != NULL && (
        strcmp(disable_wmma, "1") == 0 || strcmp(disable_wmma, "true") == 0)) {
        fprintf(stderr, "wmma_diag: disabled by HIP_QUANT_DISABLE_WMMA\n");
        return 4;
    }
    if (strstr(props.gcnArchName, "gfx12") == NULL) {
        fprintf(stderr, "wmma_diag: not a gfx12 device (%s)\n", props.gcnArchName);
        return 2;
    }
    int runtime_version = 0;
    hipRuntimeGetVersion(&runtime_version);
    if (runtime_version > 0 && runtime_version < 70200000) {
        fprintf(stderr, "wmma_diag: ROCm/HIP %d < 7.2 required\n", runtime_version);
        return 3;
    }
    return 0;
}

HIP_QUANT_EXPORT int wmma_diag(int *results_out) {
    if (!ensure_initialized()) return 1;
    if (results_out == NULL) return 1;

    for (int i = 0; i < 4; i++) results_out[i] = -1;

    int gate = wmma_diag_check_gating();
    if (gate != 0) return gate;

    const int K = 64;
    const int bytes = K * 16;
    uint8_t *h_A = (uint8_t*)malloc(bytes);
    uint8_t *h_B = (uint8_t*)malloc(bytes);
    memset(h_A, 0x38, bytes);  // FP8 E4M3 1.0
    memset(h_B, 0x38, bytes);

    uint8_t *d_A = NULL, *d_B = NULL;
    float *d_C = NULL, *d_max = NULL, *d_min = NULL;
    int *d_ok = NULL, *d_wave = NULL;
    hipError_t e;

    e = hipMalloc(&d_A, bytes);
    if (e != hipSuccess) goto fail;
    e = hipMalloc(&d_B, bytes);
    if (e != hipSuccess) goto fail;
    // Test 4 stores one 16x16 output tile for each of its 16 Wave32
    // blocks.  Allocate for that largest diagnostic result, not just the
    // single-tile buffers used by tests 1 and 3.
    e = hipMalloc(&d_C, 16 * 256 * sizeof(float));
    if (e != hipSuccess) goto fail;
    e = hipMalloc(&d_max, sizeof(float));
    if (e != hipSuccess) goto fail;
    e = hipMalloc(&d_min, sizeof(float));
    if (e != hipSuccess) goto fail;
    e = hipMalloc(&d_ok, sizeof(int));
    if (e != hipSuccess) goto fail;
    e = hipMalloc(&d_wave, 16 * sizeof(int));
    if (e != hipSuccess) goto fail;

    hipMemcpy(d_A, h_A, bytes, hipMemcpyHostToDevice);
    hipMemcpy(d_B, h_B, bytes, hipMemcpyHostToDevice);

    // === Test 1: Known values ===
    {
        hipMemset(d_C, 0, 256 * sizeof(float));
        float h_max = 0.0f, h_min = 0.0f;
        hipLaunchKernelGGL(wmma_diag_known_values_kernel, dim3(1), dim3(32), 0, 0,
            d_A, d_B, d_C, d_max, d_min, K);
        e = hipGetLastError();
        if (e != hipSuccess) {
            fprintf(stderr, "wmma_diag: Test 1 kernel launch error: %s\n", hipGetErrorString(e));
            results_out[0] = -100;
            goto fail;
        }
        e = hipDeviceSynchronize();
        if (e != hipSuccess) {
            fprintf(stderr, "wmma_diag: Test 1 sync error: %s (HANG?) \n", hipGetErrorString(e));
            results_out[0] = -200;
            goto fail;
        }
        hipMemcpy(&h_max, d_max, sizeof(float), hipMemcpyDeviceToHost);
        hipMemcpy(&h_min, d_min, sizeof(float), hipMemcpyDeviceToHost);
        results_out[0] = (int)(h_max * 1000.0f + 0.5f);  // milliscale for int
    }

    // === Test 2: Repeated accumulation ===
    {
        hipMemset(d_ok, 0, sizeof(int));
        const int n_iters = 100;
        // The diagnostic kernel is one Wave32 and is compiled with a
        // 32-thread launch bound.  Launching 64 threads violates that
        // contract on gfx12 and turns an otherwise valid WMMA diagnostic
        // into an unspecified launch failure.
        hipLaunchKernelGGL(wmma_diag_repeated_kernel, dim3(1), dim3(32), 0, 0,
            d_A, d_B, d_C, d_ok, K, n_iters);
        e = hipGetLastError();
        if (e != hipSuccess) {
            fprintf(stderr, "wmma_diag: Test 2 kernel launch error: %s\n", hipGetErrorString(e));
            results_out[1] = -100;
            goto fail;
        }
        e = hipDeviceSynchronize();
        if (e != hipSuccess) {
            fprintf(stderr, "wmma_diag: Test 2 sync error: %s\n", hipGetErrorString(e));
            results_out[1] = -200;
            goto fail;
        }
        int h_ok = 0;
        hipMemcpy(&h_ok, d_ok, sizeof(int), hipMemcpyDeviceToHost);
        results_out[1] = h_ok;  // 0 = pass, negative = failed at that iter
    }

    // === Test 3: LDS-staged WMMA ===
    {
        hipMemset(d_C, 0, 256 * sizeof(float));
        hipLaunchKernelGGL(wmma_diag_lds_stage_kernel, dim3(1), dim3(64), 0, 0,
            d_A, d_B, d_C, K);
        e = hipGetLastError();
        if (e != hipSuccess) {
            fprintf(stderr, "wmma_diag: Test 3 kernel launch error: %s\n", hipGetErrorString(e));
            results_out[2] = -100;
            goto fail;
        }
        e = hipDeviceSynchronize();
        if (e != hipSuccess) {
            fprintf(stderr, "wmma_diag: Test 3 sync error: %s\n", hipGetErrorString(e));
            results_out[2] = -200;
            goto fail;
        }
        float h_c_test3 = 0.0f;
        hipMemcpy(&h_c_test3, d_C, sizeof(float), hipMemcpyDeviceToHost);
        results_out[2] = (int)(h_c_test3 * 1000.0f + 0.5f);
    }

    // === Test 4: Multi-wave ===
    {
        hipMemset(d_C, 0, 16 * 256 * sizeof(float));
        hipMemset(d_wave, 0, 16 * sizeof(int));
        hipLaunchKernelGGL(wmma_diag_multiwave_kernel, dim3(16), dim3(32), 0, 0,
            d_A, d_B, d_C, d_wave, K);
        e = hipGetLastError();
        if (e != hipSuccess) {
            fprintf(stderr, "wmma_diag: Test 4 kernel launch error: %s\n", hipGetErrorString(e));
            results_out[3] = -100;
            goto fail;
        }
        e = hipDeviceSynchronize();
        if (e != hipSuccess) {
            fprintf(stderr, "wmma_diag: Test 4 sync error: %s\n", hipGetErrorString(e));
            results_out[3] = -200;
            goto fail;
        }
        int h_wave[16] = {0};
        hipMemcpy(h_wave, d_wave, 16 * sizeof(int), hipMemcpyDeviceToHost);
        int good_waves = 0;
        for (int i = 0; i < 16; i++) {
            if (h_wave[i] > 0) good_waves++;
        }
        results_out[3] = good_waves;
    }

    free(h_A); free(h_B);
    hipFree(d_A); hipFree(d_B); hipFree(d_C);
    hipFree(d_max); hipFree(d_min); hipFree(d_ok); hipFree(d_wave);
    return 0;

fail:
    free(h_A); free(h_B);
    if (d_A) hipFree(d_A);
    if (d_B) hipFree(d_B);
    if (d_C) hipFree(d_C);
    if (d_max) hipFree(d_max);
    if (d_min) hipFree(d_min);
    if (d_ok) hipFree(d_ok);
    if (d_wave) hipFree(d_wave);
    return 1;
}

HIP_QUANT_EXPORT void quantize_reset() {
    if (g_d_src)       { hipFree(g_d_src);       g_d_src = NULL; }
    if (g_d_src_fp8)   { hipFree(g_d_src_fp8);   g_d_src_fp8 = NULL; }
    if (g_d_dst)       { hipFree(g_d_dst);       g_d_dst = NULL; }
    if (g_d_imatrix)   { hipFree(g_d_imatrix);   g_d_imatrix = NULL; }
    g_d_src_cap = 0;
    g_d_src_fp8_cap = 0;
    g_d_dst_cap = 0;
    g_d_imatrix_cap = 0;
}

HIP_QUANT_EXPORT int get_device_count() {
    int count = 0;
    hipGetDeviceCount(&count);
    return count;
}

// ============================================================
// Device property queries for compatibility checker
// ============================================================

HIP_QUANT_EXPORT int get_device_prop(
    char *name_buf, int name_buf_size,
    int *major, int *minor,
    int *cu_count,
    size_t *total_mem,
    size_t *shared_mem_per_block,
    int *warp_size,
    int *max_threads_per_block
) {
    if (!ensure_initialized()) return 1;
    strncpy(name_buf, props.name, (size_t)(name_buf_size - 1));
    name_buf[name_buf_size - 1] = '\0';
    *major = props.major;
    *minor = props.minor;
    *cu_count = props.multiProcessorCount;
    *total_mem = props.totalGlobalMem;
    *shared_mem_per_block = props.sharedMemPerBlock;
    *warp_size = props.warpSize;
    *max_threads_per_block = props.maxThreadsPerBlock;
    return 0;
}

HIP_QUANT_EXPORT int get_arch_name(char *buf, int buf_size) {
    if (!ensure_initialized()) return 1;
    strncpy(buf, props.gcnArchName, (size_t)(buf_size - 1));
    buf[buf_size - 1] = '\0';
    return 0;
}

HIP_QUANT_EXPORT int get_hip_runtime_version() {
    int runtime_version = 0;
    hipRuntimeGetVersion(&runtime_version);
    return runtime_version;
}

HIP_QUANT_EXPORT int get_device_memory(size_t *free_bytes, size_t *total_bytes) {
    if (!ensure_initialized()) {
        *free_bytes = 0;
        *total_bytes = 0;
        return 1;
    }
    hipError_t e = hipMemGetInfo(free_bytes, total_bytes);
    if (e != hipSuccess) {
        *free_bytes = 0;
        *total_bytes = 0;
        return 1;
    }
    return 0;
}

HIP_QUANT_EXPORT int device_has_wmma() {
    if (!ensure_initialized()) return 0;
    const char *arch = props.gcnArchName;
    // This reports support for the FP8/BF8 gfx12 w32 intrinsics used by
    // fp8_gemm_wmma_kernel, not general matrix-core or rocWMMA capability.
    // CDNA has MFMA/FP8 paths, but not this RDNA4-specific builtin path.
    return (strstr(arch, "gfx12") != NULL) ? 1 : 0;
}

#ifdef __cplusplus
}
#endif
